language: cpp
compiler: gcc
dist: trusty

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - sudo add-apt-repository ppa:apokluda/boost1.53 --yes
  - sudo apt-get update

install: 
  - sudo apt-get install -qq g++-6
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90
  - sudo apt-get update

before_script:
  - mkdir build
  - cd build
  - cmake ..
script: 
  - make
  - ./main 4 < test1
  - ./main 4 < test2
